# Generated by Django 4.1.5 on 2023-01-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='video_type',
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='channel',
            field=models.CharField(max_length=100),
        ),
    ]
